import test from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync,privateDecrypt,createDecipheriv,constants} from 'node:crypto';
import {seal,estimate,review,MAX_TOOLS} from './quality-review.mjs';
const {publicKey:pem,privateKey}=generateKeyPairSync('rsa',{modulusLength:3072,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}});
function open(e){const key=privateDecrypt({key:privateKey,padding:constants.RSA_PKCS1_OAEP_PADDING,oaepHash:'sha256'},Buffer.from(e.key,'base64'));const d=createDecipheriv('aes-256-gcm',key,Buffer.from(e.iv,'base64'));d.setAuthTag(Buffer.from(e.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(e.ciphertext,'base64')),d.final()]).toString());}
const payload={model:'gpt-6-luna',tools:[{type:'web_search'}]};
const load=async({transport})=>({generate:async()=>{await transport('https://api.openai.com/v1/responses',{method:'POST',body:JSON.stringify(payload)});return [{sourceUrl:'https://www.env.go.jp/example',eventKey:'sample',prompt:'PRIVATE_QUESTION'}];},validate:()=>[]});
const mock=async(_,init)=>{const p=JSON.parse(init.body);assert.equal(p.max_tool_calls,8);assert.equal(p.max_output_tokens,16000);assert.equal(p.store,false);return Response.json({model:'gpt-6-luna',status:'completed',usage:{input_tokens:100,output_tokens:10},output:[{type:'web_search_call',action:{type:'search',sources:[]}},{type:'message',content:[{type:'output_text',text:'PRIVATE_QUESTION'}]}]});};
test('envelope decrypts; plaintext absent; tampering rejected',()=>{const e=seal({test:'PRIVATE_QUESTION'},pem);assert.equal(JSON.stringify(e).includes('PRIVATE_QUESTION'),false);assert.equal(open(e).test,'PRIVATE_QUESTION');e.tag=Buffer.alloc(16).toString('base64');assert.throws(()=>open(e));});
test('cache write premium included; invalid usage stays unknown',()=>{assert.equal(estimate({input_tokens:37049,output_tokens:1345,input_tokens_details:{cache_write_tokens:4865,cached_tokens:0}},4).model_usd,0.004499025);assert.equal(estimate({input_tokens:5,output_tokens:1,input_tokens_details:{cache_write_tokens:6}},0),null);});
test('missing credentials block before load and network',async()=>{const r=await review({pem,load:()=>assert.fail('load')});assert.equal(r.report.request_count,0);assert.equal(r.encrypted,null);});
test('one request, encrypted questions, sanitized metrics, no publish',async()=>{const r=await review({apiKey:'SECRET',pem,load,fetchImpl:mock});assert.equal(r.report.status,'generated_unpublished');assert.equal(r.report.request_count,1);assert.equal(r.report.published,0);assert.equal(r.report.structural_pass,1);assert.equal(JSON.stringify(r).includes('SECRET'),false);assert.equal(JSON.stringify(r).includes('PRIVATE_QUESTION'),false);assert.equal(open(r.encrypted).items[0].prompt,'PRIVATE_QUESTION');});
test('second call blocked without retry',async()=>{let calls=0;const r=await review({apiKey:'SECRET',pem,fetchImpl:async(...args)=>{calls++;return mock(...args);},load:async({transport})=>({generate:async()=>{await transport('https://api.openai.com/v1/responses',{method:'POST',body:JSON.stringify(payload)});await transport('https://api.openai.com/v1/responses',{method:'POST',body:JSON.stringify(payload)});},validate:()=>[]})});assert.equal(calls,1);assert.equal(r.report.status,'review_failed');});
test('wrong model blocked before request',async()=>{const r=await review({apiKey:'SECRET',pem,fetchImpl:()=>assert.fail('network'),load:async({transport})=>({generate:()=>transport('https://api.openai.com/v1/responses',{method:'POST',body:JSON.stringify({...payload,model:'gpt-5.6'})}),validate:()=>[]})});assert.equal(r.report.request_count,0);});
test('provider failures never disclose raw error',async()=>{const r=await review({apiKey:'SECRET',pem,load,fetchImpl:()=>{throw new Error('SECRET');}});assert.equal(r.report.status,'review_failed');assert.equal(r.report.request_count,1);assert.equal(JSON.stringify(r).includes('SECRET'),false);});
